apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sky-be-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app.kubernetes.io/instance: sky-be-stg-aws
      app.kubernetes.io/name: common-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - targetLabel: job
          replacement: sky-api
