"""Add widget feedback table and relationships

Revision ID: 14398128edd5
Revises: add_ai_feedback
Create Date: 2026-01-21 09:35:26.801030

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '14398128edd5'
down_revision = 'add_ai_feedback'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False, comment='1 for like, -1 for dislike'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_widget_feedback_widget_user', 'widget_feedback', ['widget_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_widget_feedback_user_id'), 'widget_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_widget_feedback_widget_id'), 'widget_feedback', ['widget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_feedback_widget_id'), table_name='widget_feedback')
    op.drop_index(op.f('ix_widget_feedback_user_id'), table_name='widget_feedback')
    op.drop_index('idx_widget_feedback_widget_user', table_name='widget_feedback')
    op.drop_table('widget_feedback')
    # ### end Alembic commands ###

