"""add_strategy_tables

Revision ID: 219c9bf1679e
Revises: 5841f6a73c66
Create Date: 2026-03-03 14:37:30.459660

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "219c9bf1679e"
down_revision = "5841f6a73c66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategic_pillars",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategic_objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pillar_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("horizon", sa.String(length=50), nullable=True),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("owner_crew_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_crew_id"], ["crews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["pillar_id"], ["strategic_pillars.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_initiatives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_crew_id", sa.UUID(), nullable=True),
        sa.Column("budget_estimated", sa.Float(), nullable=True),
        sa.Column("expected_impact", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alignment_score", sa.Integer(), nullable=True),
        sa.Column("supports_objectives", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_crew_id"], ["crews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_assumptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidence", sa.String(length=50), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("revision_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_crew_id", sa.UUID(), nullable=True),
        sa.Column("linked_objective_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["linked_objective_id"], ["strategic_objectives.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_crew_id"], ["crews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_okrs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("objective_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("linked_kpi_id", sa.String(length=100), nullable=True),
        sa.Column("baseline", sa.Float(), nullable=True),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("measurement_frequency", sa.String(length=50), nullable=True),
        sa.Column("owner_crew_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"], ["strategic_objectives.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_crew_id"], ["crews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strategy_key_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("okr_id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("baseline", sa.Float(), nullable=True),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["okr_id"], ["strategy_okrs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strategy_key_results")
    op.drop_table("strategy_okrs")
    op.drop_table("strategy_assumptions")
    op.drop_table("strategy_initiatives")
    op.drop_table("strategic_objectives")
    op.drop_table("strategic_pillars")
    # ### end Alembic commands ###
