"""add intelligence signals table

Revision ID: 4ee65fd7eb1f
Revises: 12f9e8513551
Create Date: 2026-03-11 09:03:18.110878

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4ee65fd7eb1f"
down_revision = "12f9e8513551"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intelligence_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("planet_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("color", sa.String(length=50), nullable=True),
        sa.Column("cta_label", sa.String(length=255), nullable=True),
        sa.Column("cta_action", sa.String(length=100), nullable=True),
        sa.Column("cta_params", sa.JSON(), nullable=True),
        sa.Column("chart_data", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_dismissed", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["planet_id"], ["planets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intelligence_signals_category"),
        "intelligence_signals",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intelligence_signals_planet_id"),
        "intelligence_signals",
        ["planet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intelligence_signals_space_id"),
        "intelligence_signals",
        ["space_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intelligence_signals_space_id"), table_name="intelligence_signals"
    )
    op.drop_index(
        op.f("ix_intelligence_signals_planet_id"), table_name="intelligence_signals"
    )
    op.drop_index(
        op.f("ix_intelligence_signals_category"), table_name="intelligence_signals"
    )
    # ### end Alembic commands ###
