"""Add signal events table

Revision ID: 5841f6a73c66
Revises: b3dbb2cec04c
Create Date: 2026-03-02 14:59:40.343828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5841f6a73c66'
down_revision = 'b3dbb2cec04c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('INTERNAL', 'EXTERNAL', 'TRENDS', name='signalcategory'), nullable=False),
    sa.Column('sub_type', sa.String(length=100), nullable=False),
    sa.Column('nature', sa.Enum('EVENT', 'SIGNAL', 'HYPOTHESIS', name='signalnature'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('impact_date', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='signalconfidence'), nullable=False),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_chat_history_thread_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_table('table_metadata')
    op.drop_index('idx_user_datasets_dataset_id', table_name='user_datasets')
    op.drop_index('idx_user_datasets_user_id', table_name='user_datasets')
    op.drop_index('ix_user_datasets_user_id', table_name='user_datasets')
    op.drop_table('user_datasets')
    op.drop_table('checkpoints')
    op.drop_index('idx_audit_connection', table_name='query_audit_log')
    op.drop_index('idx_audit_escalation', table_name='query_audit_log', postgresql_where='(progressive_escalation_detected = true)')
    op.drop_index('idx_audit_pii_blocked', table_name='query_audit_log', postgresql_where='(pii_blocked = true)')
    op.drop_index('idx_audit_pii_detected', table_name='query_audit_log', postgresql_where='((pii_detected_in_prompt = true) OR (pii_detected_in_response = true))')
    op.drop_index('idx_audit_prompt_injection', table_name='query_audit_log', postgresql_where='(prompt_injection_detected = true)')
    op.drop_index('idx_audit_space', table_name='query_audit_log')
    op.drop_index('idx_audit_thread', table_name='query_audit_log')
    op.drop_index('idx_audit_timestamp', table_name='query_audit_log')
    op.drop_index('idx_audit_user', table_name='query_audit_log')
    op.drop_table('query_audit_log')
    op.drop_index('idx_alerts_severity', table_name='security_alerts')
    op.drop_index('idx_alerts_type', table_name='security_alerts')
    op.drop_index('idx_alerts_user', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index('idx_prompt_audit_connection', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_status', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_timestamp', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_user', table_name='prompt_security_audit')
    op.drop_table('prompt_security_audit')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crew_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='user_permissions_crew_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_permissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_permissions_pkey')
    )
    op.create_table('prompt_security_audit',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prompt_text_redacted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('security_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('blocked_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scan_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prompt_security_audit_pkey')
    )
    op.create_index('idx_prompt_audit_user', 'prompt_security_audit', ['user_id'], unique=False)
    op.create_index('idx_prompt_audit_timestamp', 'prompt_security_audit', ['timestamp'], unique=False)
    op.create_index('idx_prompt_audit_status', 'prompt_security_audit', ['security_status'], unique=False)
    op.create_index('idx_prompt_audit_connection', 'prompt_security_audit', ['connection_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_alerts_pkey')
    )
    op.create_index('idx_alerts_user', 'security_alerts', ['user_id'], unique=False)
    op.create_index('idx_alerts_type', 'security_alerts', ['alert_type'], unique=False)
    op.create_index('idx_alerts_severity', 'security_alerts', ['severity'], unique=False)
    op.create_table('query_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crew_ids', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('platform_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('crew_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql_generated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_executed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_validated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('num_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('was_rate_limited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('prompt_injection_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('prompt_injection_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progressive_escalation_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('progressive_escalation_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('detected_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('chosen_tables', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('answer_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pii_detected_in_prompt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pii_detected_in_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pii_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pii_severity', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('pii_patterns_matched', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pii_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='query_audit_log_pkey')
    )
    op.create_index('idx_audit_user', 'query_audit_log', ['user_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'query_audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_thread', 'query_audit_log', ['thread_id'], unique=False)
    op.create_index('idx_audit_space', 'query_audit_log', ['space_id'], unique=False)
    op.create_index('idx_audit_prompt_injection', 'query_audit_log', ['prompt_injection_detected'], unique=False, postgresql_where='(prompt_injection_detected = true)')
    op.create_index('idx_audit_pii_detected', 'query_audit_log', ['pii_detected_in_prompt', 'pii_detected_in_response'], unique=False, postgresql_where='((pii_detected_in_prompt = true) OR (pii_detected_in_response = true))')
    op.create_index('idx_audit_pii_blocked', 'query_audit_log', ['pii_blocked'], unique=False, postgresql_where='(pii_blocked = true)')
    op.create_index('idx_audit_escalation', 'query_audit_log', ['progressive_escalation_detected'], unique=False, postgresql_where='(progressive_escalation_detected = true)')
    op.create_index('idx_audit_connection', 'query_audit_log', ['connection_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id', name='checkpoints_pkey')
    )
    op.create_table('user_datasets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dataset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-12-31 12:20:53.610844+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_datasets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_datasets_pkey'),
    sa.UniqueConstraint('user_id', 'dataset_id', name='uq_user_datasets')
    )
    op.create_index('ix_user_datasets_user_id', 'user_datasets', ['user_id'], unique=False)
    op.create_index('idx_user_datasets_user_id', 'user_datasets', ['user_id'], unique=False)
    op.create_index('idx_user_datasets_dataset_id', 'user_datasets', ['dataset_id'], unique=False)
    op.create_table('table_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crew_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='table_metadata_crew_id_fkey'),
    sa.ForeignKeyConstraint(['data_connection_id'], ['data_connections.id'], name='table_metadata_data_connection_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='table_metadata_space_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='table_metadata_pkey')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_index('ix_chat_history_thread_id', 'chat_history', ['thread_id'], unique=False)
    op.drop_table('signal_events')
    # ### end Alembic commands ###

