"""Add signal events table

Revision ID: 5841f6a73c66
Revises: b3dbb2cec04c
Create Date: 2026-03-02 14:59:40.343828

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5841f6a73c66'
down_revision = 'b3dbb2cec04c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('INTERNAL', 'EXTERNAL', 'TRENDS', name='signalcategory'), nullable=False),
    sa.Column('sub_type', sa.String(length=100), nullable=False),
    sa.Column('nature', sa.Enum('EVENT', 'SIGNAL', 'HYPOTHESIS', name='signalnature'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('impact_date', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='signalconfidence'), nullable=False),
    sa.Column('relations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_events')
    # ### end Alembic commands ###
