"""update_strategy_models_to_match_frontend

Revision ID: 65904bc5a0f4
Revises: 219c9bf1679e
Create Date: 2026-03-03 16:40:46.973124

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "65904bc5a0f4"
down_revision = "219c9bf1679e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategic_objectives", sa.Column("status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "strategic_objectives", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.add_column("strategic_objectives", sa.Column("kpis", sa.JSON(), nullable=True))
    op.add_column(
        "strategic_objectives", sa.Column("budget", sa.Float(), nullable=True)
    )
    op.drop_column("strategic_objectives", "horizon")
    op.drop_column("strategic_objectives", "weight")
    op.add_column(
        "strategic_pillars", sa.Column("horizon", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "strategic_pillars", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.add_column("strategic_pillars", sa.Column("metrics", sa.JSON(), nullable=True))
    op.add_column(
        "strategic_pillars", sa.Column("priority", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("category", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "strategy_assumptions", sa.Column("impact_score", sa.Integer(), nullable=True)
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("probability_score", sa.Integer(), nullable=True),
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("priority", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "strategy_assumptions", sa.Column("impacted_entities", sa.JSON(), nullable=True)
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("source", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "strategy_assumptions", sa.Column("status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "strategy_assumptions", sa.Column("mitigation_plan", sa.Text(), nullable=True)
    )
    op.add_column(
        "strategy_assumptions", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.drop_constraint(
        "strategy_assumptions_owner_crew_id_fkey",
        "strategy_assumptions",
        type_="foreignkey",
    )
    op.drop_column("strategy_assumptions", "revision_deadline")
    op.drop_column("strategy_assumptions", "owner_crew_id")
    op.drop_column("strategy_assumptions", "validated")
    op.drop_column("strategy_assumptions", "confidence")
    op.add_column(
        "strategy_initiatives", sa.Column("type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "strategy_initiatives", sa.Column("pillar_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "strategy_initiatives", sa.Column("objective_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "strategy_initiatives", sa.Column("unit", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "strategy_initiatives", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.add_column("strategy_initiatives", sa.Column("impact", sa.Text(), nullable=True))
    op.add_column(
        "strategy_initiatives", sa.Column("budget", sa.Float(), nullable=True)
    )
    op.add_column("strategy_initiatives", sa.Column("risks", sa.JSON(), nullable=True))
    op.add_column(
        "strategy_initiatives", sa.Column("assumptions", sa.JSON(), nullable=True)
    )
    op.add_column(
        "strategy_initiatives", sa.Column("progress", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "strategy_initiatives_owner_crew_id_fkey",
        "strategy_initiatives",
        type_="foreignkey",
    )
    op.drop_column("strategy_initiatives", "owner_crew_id")
    op.drop_column("strategy_initiatives", "alignment_score")
    op.drop_column("strategy_initiatives", "supports_objectives")
    op.drop_column("strategy_initiatives", "budget_estimated")
    op.drop_column("strategy_initiatives", "expected_impact")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "strategy_initiatives",
        sa.Column("expected_impact", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "strategy_initiatives",
        sa.Column(
            "budget_estimated",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "strategy_initiatives",
        sa.Column(
            "supports_objectives",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "strategy_initiatives",
        sa.Column("alignment_score", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "strategy_initiatives",
        sa.Column("owner_crew_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "strategy_initiatives_owner_crew_id_fkey",
        "strategy_initiatives",
        "crews",
        ["owner_crew_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("strategy_initiatives", "progress")
    op.drop_column("strategy_initiatives", "assumptions")
    op.drop_column("strategy_initiatives", "risks")
    op.drop_column("strategy_initiatives", "budget")
    op.drop_column("strategy_initiatives", "impact")
    op.drop_column("strategy_initiatives", "owner")
    op.drop_column("strategy_initiatives", "unit")
    op.drop_column("strategy_initiatives", "objective_id")
    op.drop_column("strategy_initiatives", "pillar_id")
    op.drop_column("strategy_initiatives", "type")
    op.add_column(
        "strategy_assumptions",
        sa.Column(
            "confidence", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("validated", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column("owner_crew_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "strategy_assumptions",
        sa.Column(
            "revision_deadline",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "strategy_assumptions_owner_crew_id_fkey",
        "strategy_assumptions",
        "crews",
        ["owner_crew_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("strategy_assumptions", "owner")
    op.drop_column("strategy_assumptions", "mitigation_plan")
    op.drop_column("strategy_assumptions", "status")
    op.drop_column("strategy_assumptions", "source")
    op.drop_column("strategy_assumptions", "impacted_entities")
    op.drop_column("strategy_assumptions", "priority")
    op.drop_column("strategy_assumptions", "probability_score")
    op.drop_column("strategy_assumptions", "impact_score")
    op.drop_column("strategy_assumptions", "category")
    op.drop_column("strategic_pillars", "priority")
    op.drop_column("strategic_pillars", "metrics")
    op.drop_column("strategic_pillars", "owner")
    op.drop_column("strategic_pillars", "horizon")
    op.add_column(
        "strategic_objectives",
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "strategic_objectives",
        sa.Column("horizon", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_column("strategic_objectives", "budget")
    op.drop_column("strategic_objectives", "kpis")
    op.drop_column("strategic_objectives", "owner")
    op.drop_column("strategic_objectives", "status")
    # ### end Alembic commands ###
