"""Add planet_id to AI models for tenant isolation

Revision ID: 6ce048ffd0c4
Revises: b912b9ad4a0b
Create Date: 2026-02-20 10:10:29.181753

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ce048ffd0c4'
down_revision = 'b912b9ad4a0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- ai_history ---
    op.add_column('ai_history', sa.Column('planet_id', sa.UUID(), nullable=True))
    op.create_index('idx_ai_history_planet_id', 'ai_history', ['planet_id'], unique=False)
    op.create_index('idx_ai_history_planet_created', 'ai_history', ['planet_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_ai_history_planet_id_planets', 'ai_history', 'planets', ['planet_id'], ['id'], ondelete='CASCADE')

    # --- ai_queries ---
    op.add_column('ai_queries', sa.Column('planet_id', sa.UUID(), nullable=True))
    op.create_index('idx_ai_queries_planet_id', 'ai_queries', ['planet_id'], unique=False)
    op.create_index('idx_ai_queries_planet_created', 'ai_queries', ['planet_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_ai_queries_planet_id_planets', 'ai_queries', 'planets', ['planet_id'], ['id'], ondelete='CASCADE')

    # --- chat_messages ---
    op.add_column('chat_messages', sa.Column('planet_id', sa.UUID(), nullable=True))
    op.create_index('idx_chat_messages_planet_id', 'chat_messages', ['planet_id'], unique=False)
    op.create_index('idx_chat_messages_planet_created', 'chat_messages', ['planet_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_chat_messages_planet_id_planets', 'chat_messages', 'planets', ['planet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- chat_messages ---
    op.drop_constraint('fk_chat_messages_planet_id_planets', 'chat_messages', type_='foreignkey')
    op.drop_index('idx_chat_messages_planet_created', table_name='chat_messages')
    op.drop_index('idx_chat_messages_planet_id', table_name='chat_messages')
    op.drop_column('chat_messages', 'planet_id')

    # --- ai_queries ---
    op.drop_constraint('fk_ai_queries_planet_id_planets', 'ai_queries', type_='foreignkey')
    op.drop_index('idx_ai_queries_planet_created', table_name='ai_queries')
    op.drop_index('idx_ai_queries_planet_id', table_name='ai_queries')
    op.drop_column('ai_queries', 'planet_id')

    # --- ai_history ---
    op.drop_constraint('fk_ai_history_planet_id_planets', 'ai_history', type_='foreignkey')
    op.drop_index('idx_ai_history_planet_created', table_name='ai_history')
    op.drop_index('idx_ai_history_planet_id', table_name='ai_history')
    op.drop_column('ai_history', 'planet_id')
    # ### end Alembic commands ###

