"""Add space privacy fields

Revision ID: 7596a081b418
Revises: a0ded69bb18d
Create Date: 2026-02-16 14:52:09.551987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7596a081b418'
down_revision = 'a0ded69bb18d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('privacy', sa.String(length=50), server_default='private', nullable=False))
    op.add_column('spaces', sa.Column('sensitivity', sa.String(length=50), server_default='internal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'sensitivity')
    op.drop_column('spaces', 'privacy')
    # ### end Alembic commands ###

