"""Add user activity fields

Revision ID: a0ded69bb18d
Revises: b912b9ad4a0b
Create Date: 2026-02-16 14:32:45.912218

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a0ded69bb18d'
down_revision = 'b912b9ad4a0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'last_active_at' not in columns:
        op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    if 'status' not in columns:
        op.add_column('users', sa.Column('status', sa.String(length=50), server_default='offline', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'last_active_at')
    # ### end Alembic commands ###

