"""add_strategy_cycles

Revision ID: a1009ce57bec
Revises: c1d2e3f4a5b6
Create Date: 2026-03-06 12:49:23.230954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1009ce57bec'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('strategy_okrs', sa.Column('cycle_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_okr_cycle_id', 'strategy_okrs', 'strategy_cycles', ['cycle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_okr_cycle_id', 'strategy_okrs', type_='foreignkey')
    op.drop_column('strategy_okrs', 'cycle_id')
    op.drop_table('strategy_cycles')
    # ### end Alembic commands ###
