"""Add user preferences column

Revision ID: add08fee17ca
Revises: 14398128edd5
Create Date: 2026-01-21 10:29:49.563416

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "add08fee17ca"
down_revision = "14398128edd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "preferences",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'{}'::json"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferences")
    # ### end Alembic commands ###
