"""add connection permissions table

Revision ID: b912b9ad4a0b
Revises: 3f17472d08d9
Create Date: 2026-01-26 17:02:06.687004

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b912b9ad4a0b"
down_revision = "3f17472d08d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("space_id", sa.UUID(), nullable=True),
        sa.Column("crew_id", sa.UUID(), nullable=True),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("table_access", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["data_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["crew_id"], ["crews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id", "space_id", "crew_id", name="uq_connection_permissions"
        ),
    )
    op.create_index(
        "idx_connection_permissions_connection_id",
        "connection_permissions",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        "idx_connection_permissions_crew_id",
        "connection_permissions",
        ["crew_id"],
        unique=False,
    )
    op.create_index(
        "idx_connection_permissions_space_id",
        "connection_permissions",
        ["space_id"],
        unique=False,
    )

    op.create_table(
        "table_member_permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column("crew_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column(
            "has_access", sa.String(length=10), server_default="true", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default="now()",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["data_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["crew_id"], ["crews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["member_id"], ["crew_members.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connection_id",
            "table_name",
            "member_id",
            name="uq_table_member_permissions",
        ),
    )
    op.create_index(
        "idx_table_member_permissions_connection_id",
        "table_member_permissions",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        "idx_table_member_permissions_crew_id",
        "table_member_permissions",
        ["crew_id"],
        unique=False,
    )
    op.create_index(
        "idx_table_member_permissions_member_id",
        "table_member_permissions",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        "idx_table_member_permissions_table_name",
        "table_member_permissions",
        ["table_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_table_member_permissions_table_name", table_name="table_member_permissions"
    )
    op.drop_index(
        "idx_table_member_permissions_member_id", table_name="table_member_permissions"
    )
    op.drop_index(
        "idx_table_member_permissions_crew_id", table_name="table_member_permissions"
    )
    op.drop_index(
        "idx_table_member_permissions_connection_id",
        table_name="table_member_permissions",
    )
    op.drop_index(
        "idx_connection_permissions_space_id", table_name="connection_permissions"
    )
    op.drop_index(
        "idx_connection_permissions_crew_id", table_name="connection_permissions"
    )
    op.drop_index(
        "idx_connection_permissions_connection_id", table_name="connection_permissions"
    )
    # ### end Alembic commands ###
