"""Backfill space/crew creators as members.

Historically, creating a space or crew only set `created_by` but never
inserted a corresponding `space_members` / `crew_members` row for the
creator. That left creators invisible in the members list and absent from
the collaborative presence pill.

This migration:
  1. Inserts a `space_members` row for every (space.id, space.created_by)
     pair that does not already have one.
  2. Inserts a `crew_members` row (role='commander') for every
     (crew.id, crew.created_by) pair that does not already have one.

Revision ID: backfill_creator_membership_20260414
Revises: add_notification_preferences_20260412
Create Date: 2026-04-14 12:00:00.000000
"""

from alembic import op


# revision identifiers
revision = "backfill_creator_membership_20260414"
down_revision = "add_notification_preferences_20260412"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Backfill space creators as members.
    # id is generated by pgcrypto (gen_random_uuid), created_at falls back
    # to server_default=NOW().
    op.execute(
        """
        INSERT INTO space_members (id, space_id, user_id)
        SELECT gen_random_uuid(), s.id, s.created_by
        FROM spaces s
        WHERE s.created_by IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM space_members sm
              WHERE sm.space_id = s.id
                AND sm.user_id = s.created_by
          )
        """
    )

    # Backfill crew creators as members (role: commander).
    # id generated, joined_at/created_at fall back to server defaults.
    op.execute(
        """
        INSERT INTO crew_members (id, crew_id, user_id, role)
        SELECT gen_random_uuid(), c.id, c.created_by, 'commander'
        FROM crews c
        WHERE c.created_by IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM crew_members cm
              WHERE cm.crew_id = c.id
                AND cm.user_id = c.created_by
          )
        """
    )


def downgrade() -> None:
    # No-op: we can't safely distinguish backfilled rows from legitimate
    # manual additions, and removing members is destructive.
    pass
