"""add_space_tables_association

Revision ID: c7c41ef7426d
Revises: 2bf51e427a29
Create Date: 2026-02-26 16:16:13.740309

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7c41ef7426d"
down_revision = "2bf51e427a29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space_tables",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("space_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("connection_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column("schema_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["data_connections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["space_id"], ["spaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_space_tables_space_conn_table",
        "space_tables",
        ["space_id", "connection_id", "table_name", "schema_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_space_tables_connection_id"),
        "space_tables",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_space_tables_space_id"), "space_tables", ["space_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_space_tables_space_id"), table_name="space_tables")
    op.drop_index(op.f("ix_space_tables_connection_id"), table_name="space_tables")
    op.drop_index("idx_space_tables_space_conn_table", table_name="space_tables")
    # ### end Alembic commands ###
