"""expand_scopes_strategy_signals

Revision ID: cb8301f3fd27
Revises: fd74af4b3c14
Create Date: 2026-03-16 16:34:38.768667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb8301f3fd27'
down_revision = 'fd74af4b3c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intelligence_signals', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.alter_column('intelligence_signals', 'space_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='space_id::uuid')
    op.create_index(op.f('ix_intelligence_signals_crew_id'), 'intelligence_signals', ['crew_id'], unique=False)
    op.create_foreign_key(None, 'intelligence_signals', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'intelligence_signals', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.add_column('signal_events', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('signal_events', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.alter_column('signal_events', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.create_index(op.f('ix_signal_events_crew_id'), 'signal_events', ['crew_id'], unique=False)
    op.create_index(op.f('ix_signal_events_space_id'), 'signal_events', ['space_id'], unique=False)
    op.create_foreign_key(None, 'signal_events', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'signal_events', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategic_objectives', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategic_objectives', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategic_objectives_crew_id'), 'strategic_objectives', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategic_objectives_space_id'), 'strategic_objectives', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategic_objectives', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategic_objectives', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategy_okrs', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategy_okrs', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategy_okrs_crew_id'), 'strategy_okrs', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategy_okrs_space_id'), 'strategy_okrs', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategy_okrs', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_okrs', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_okrs', type_='foreignkey')
    op.drop_constraint(None, 'strategy_okrs', type_='foreignkey')
    op.drop_index(op.f('ix_strategy_okrs_space_id'), table_name='strategy_okrs')
    op.drop_index(op.f('ix_strategy_okrs_crew_id'), table_name='strategy_okrs')
    op.drop_column('strategy_okrs', 'crew_id')
    op.drop_column('strategy_okrs', 'space_id')
    op.drop_constraint(None, 'strategic_objectives', type_='foreignkey')
    op.drop_constraint(None, 'strategic_objectives', type_='foreignkey')
    op.drop_index(op.f('ix_strategic_objectives_space_id'), table_name='strategic_objectives')
    op.drop_index(op.f('ix_strategic_objectives_crew_id'), table_name='strategic_objectives')
    op.drop_column('strategic_objectives', 'crew_id')
    op.drop_column('strategic_objectives', 'space_id')
    op.drop_constraint(None, 'signal_events', type_='foreignkey')
    op.drop_constraint(None, 'signal_events', type_='foreignkey')
    op.drop_index(op.f('ix_signal_events_space_id'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_crew_id'), table_name='signal_events')
    op.alter_column('signal_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('signal_events', 'crew_id')
    op.drop_column('signal_events', 'space_id')
    op.drop_constraint(None, 'intelligence_signals', type_='foreignkey')
    op.drop_constraint(None, 'intelligence_signals', type_='foreignkey')
    op.drop_index(op.f('ix_intelligence_signals_crew_id'), table_name='intelligence_signals')
    op.alter_column('intelligence_signals', 'space_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('intelligence_signals', 'crew_id')
    # ### end Alembic commands ###

