"""add_session_metadata_to_refresh_tokens

Revision ID: ee8c60ac46f7
Revises: add08fee17ca
Create Date: 2026-01-23 09:40:04.370399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee8c60ac46f7'
down_revision = 'add08fee17ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_severity', table_name='security_alerts')
    op.drop_index('idx_alerts_type', table_name='security_alerts')
    op.drop_index('idx_alerts_user', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index('idx_prompt_audit_connection', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_status', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_timestamp', table_name='prompt_security_audit')
    op.drop_index('idx_prompt_audit_user', table_name='prompt_security_audit')
    op.drop_table('prompt_security_audit')
    op.drop_index('idx_audit_connection', table_name='query_audit_log')
    op.drop_index('idx_audit_escalation', table_name='query_audit_log', postgresql_where='(progressive_escalation_detected = true)')
    op.drop_index('idx_audit_pii_blocked', table_name='query_audit_log', postgresql_where='(pii_blocked = true)')
    op.drop_index('idx_audit_pii_detected', table_name='query_audit_log', postgresql_where='((pii_detected_in_prompt = true) OR (pii_detected_in_response = true))')
    op.drop_index('idx_audit_prompt_injection', table_name='query_audit_log', postgresql_where='(prompt_injection_detected = true)')
    op.drop_index('idx_audit_space', table_name='query_audit_log')
    op.drop_index('idx_audit_thread', table_name='query_audit_log')
    op.drop_index('idx_audit_timestamp', table_name='query_audit_log')
    op.drop_index('idx_audit_user', table_name='query_audit_log')
    op.drop_table('query_audit_log')
    op.create_index(op.f('ix_ai_feedback_query_id'), 'ai_feedback', ['query_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_user_id'), 'ai_feedback', ['user_id'], unique=False)
    op.alter_column('comments', 'mentions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_space_id', table_name='notifications')
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_constraint('notifications_space_id_fkey', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'space_id')
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.drop_constraint('role_permissions_role_key', 'role_permissions', type_='unique')
    op.drop_index('idx_role_permissions_role', table_name='role_permissions')
    op.create_index('idx_role_permissions_role', 'role_permissions', ['role'], unique=False)
    op.create_index(op.f('ix_role_permissions_role'), 'role_permissions', ['role'], unique=True)
    op.alter_column('users', 'sso_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_users_auth_provider_id', table_name='users', postgresql_where='((auth_provider_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.create_index(op.f('ix_users_auth_provider_id'), 'users', ['auth_provider_id'], unique=False)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.drop_index(op.f('ix_users_auth_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_index('idx_users_auth_provider_id', 'users', ['auth_provider_id'], unique=False, postgresql_where='((auth_provider_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.alter_column('users', 'sso_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_role_permissions_role'), table_name='role_permissions')
    op.drop_index('idx_role_permissions_role', table_name='role_permissions')
    op.create_index('idx_role_permissions_role', 'role_permissions', ['role'], unique=True)
    op.create_unique_constraint('role_permissions_role_key', 'role_permissions', ['role'])
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.add_column('notifications', sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-15 12:05:49.364629+00'::timestamp with time zone"), autoincrement=False, nullable=False))
    op.create_foreign_key('notifications_space_id_fkey', 'notifications', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.create_index('ix_notifications_space_id', 'notifications', ['space_id'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.alter_column('notifications', 'entity_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('comments', 'mentions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_query_id'), table_name='ai_feedback')
    op.create_table('query_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crew_ids', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql_generated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_executed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_validated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('validation_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('num_rows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('was_rate_limited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('prompt_injection_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('prompt_injection_pattern', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progressive_escalation_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('progressive_escalation_detected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('detected_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('chosen_tables', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('answer_preview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pii_detected_in_prompt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pii_detected_in_response', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pii_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pii_severity', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('pii_patterns_matched', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pii_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='query_audit_log_pkey')
    )
    op.create_index('idx_audit_user', 'query_audit_log', ['user_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'query_audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_thread', 'query_audit_log', ['thread_id'], unique=False)
    op.create_index('idx_audit_space', 'query_audit_log', ['space_id'], unique=False)
    op.create_index('idx_audit_prompt_injection', 'query_audit_log', ['prompt_injection_detected'], unique=False, postgresql_where='(prompt_injection_detected = true)')
    op.create_index('idx_audit_pii_detected', 'query_audit_log', ['pii_detected_in_prompt', 'pii_detected_in_response'], unique=False, postgresql_where='((pii_detected_in_prompt = true) OR (pii_detected_in_response = true))')
    op.create_index('idx_audit_pii_blocked', 'query_audit_log', ['pii_blocked'], unique=False, postgresql_where='(pii_blocked = true)')
    op.create_index('idx_audit_escalation', 'query_audit_log', ['progressive_escalation_detected'], unique=False, postgresql_where='(progressive_escalation_detected = true)')
    op.create_index('idx_audit_connection', 'query_audit_log', ['connection_id'], unique=False)
    op.create_table('prompt_security_audit',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('prompt_text_redacted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('security_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('blocked_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scan_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='prompt_security_audit_pkey')
    )
    op.create_index('idx_prompt_audit_user', 'prompt_security_audit', ['user_id'], unique=False)
    op.create_index('idx_prompt_audit_timestamp', 'prompt_security_audit', ['timestamp'], unique=False)
    op.create_index('idx_prompt_audit_status', 'prompt_security_audit', ['security_status'], unique=False)
    op.create_index('idx_prompt_audit_connection', 'prompt_security_audit', ['connection_id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='security_alerts_pkey')
    )
    op.create_index('idx_alerts_user', 'security_alerts', ['user_id'], unique=False)
    op.create_index('idx_alerts_type', 'security_alerts', ['alert_type'], unique=False)
    op.create_index('idx_alerts_severity', 'security_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###

