"""Make planet_id NOT NULL in AI models

Revision ID: f17ab2df9283
Revises: 6ce048ffd0c4
Create Date: 2026-02-20 10:13:16.349359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f17ab2df9283'
down_revision = '6ce048ffd0c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- ai_history ---
    op.alter_column('ai_history', 'planet_id',
               existing_type=sa.UUID(),
               nullable=False)

    # --- ai_queries ---
    op.alter_column('ai_queries', 'planet_id',
               existing_type=sa.UUID(),
               nullable=False)

    # --- chat_messages ---
    op.alter_column('chat_messages', 'planet_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- chat_messages ---
    op.alter_column('chat_messages', 'planet_id',
               existing_type=sa.UUID(),
               nullable=True)

    # --- ai_queries ---
    op.alter_column('ai_queries', 'planet_id',
               existing_type=sa.UUID(),
               nullable=True)

    # --- ai_history ---
    op.alter_column('ai_history', 'planet_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

