"""add_scope_to_strategy_models_fixed

Revision ID: fd74af4b3c14
Revises: dbb9a0420d3e
Create Date: 2026-03-13 15:29:30.398502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd74af4b3c14'
down_revision = 'dbb9a0420d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('universe_configs')
    op.drop_table('embeddings')
    op.drop_table('user_permissions')
    op.drop_table('checkpoints')
    op.drop_index('ix_semantic_cache_connection_id', table_name='semantic_cache')
    op.drop_index('ix_semantic_cache_crew_id', table_name='semantic_cache')
    op.drop_index('ix_semantic_cache_space_id', table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_table('pipeline_jobs')
    op.drop_table('table_metadata')
    op.drop_table('universe_insights')
    op.drop_index('idx_user_datasets_dataset_id', table_name='user_datasets')
    op.drop_index('idx_user_datasets_user_id', table_name='user_datasets')
    op.drop_table('user_datasets')
    op.drop_index('ix_chat_history_thread_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_table('query_audit_log')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.create_index('idx_ai_history_crew_id', 'ai_history', ['crew_id'], unique=False)
    op.create_index('idx_ai_history_space_id', 'ai_history', ['space_id'], unique=False)
    op.create_index(op.f('ix_ai_history_date'), 'ai_history', ['date'], unique=False)
    op.create_index(op.f('ix_ai_history_pinned'), 'ai_history', ['pinned'], unique=False)
    op.create_index(op.f('ix_ai_history_user_id'), 'ai_history', ['user_id'], unique=False)
    op.drop_column('ai_history', 'deleted_at')
    op.create_index(op.f('ix_ai_queries_user_id'), 'ai_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_queries_widget_id'), 'ai_queries', ['widget_id'], unique=False)
    op.create_index(op.f('ix_ai_responses_is_active'), 'ai_responses', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_responses_timestamp'), 'ai_responses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_responses_widget_id'), 'ai_responses', ['widget_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_widget_id'), 'chat_messages', ['widget_id'], unique=False)
    op.drop_index('idx_comments_dashboard_id', table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_widget_id', table_name='comments')
    op.create_index(op.f('ix_comments_dashboard_id'), 'comments', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_widget_id'), 'comments', ['widget_id'], unique=False)
    op.drop_constraint('uq_connection_metadata_connection_id', 'connection_metadata', type_='unique')
    op.create_index(op.f('ix_connection_metadata_connection_id'), 'connection_metadata', ['connection_id'], unique=True)
    op.create_index(op.f('ix_connection_permissions_connection_id'), 'connection_permissions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_crew_id'), 'connection_permissions', ['crew_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_space_id'), 'connection_permissions', ['space_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_user_id'), 'connection_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_crew_connections_connection_id'), 'crew_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_crew_connections_crew_id'), 'crew_connections', ['crew_id'], unique=False)
    op.create_index(op.f('ix_crew_members_crew_id'), 'crew_members', ['crew_id'], unique=False)
    op.create_index(op.f('ix_crew_members_user_id'), 'crew_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_crews_space_id'), 'crews', ['space_id'], unique=False)
    op.drop_index('idx_dashboard_build_jobs_connection_id', table_name='dashboard_build_jobs')
    op.drop_index('idx_dashboard_build_jobs_dashboard_id', table_name='dashboard_build_jobs')
    op.drop_index('idx_dashboard_build_jobs_planet_id', table_name='dashboard_build_jobs')
    op.drop_index('idx_dashboard_build_jobs_space_id', table_name='dashboard_build_jobs')
    op.drop_index('idx_dashboard_build_jobs_status', table_name='dashboard_build_jobs')
    op.drop_index('idx_dashboard_build_jobs_user_id', table_name='dashboard_build_jobs')
    op.create_index(op.f('ix_dashboard_build_jobs_connection_id'), 'dashboard_build_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_dashboard_id'), 'dashboard_build_jobs', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_planet_id'), 'dashboard_build_jobs', ['planet_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_space_id'), 'dashboard_build_jobs', ['space_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_status'), 'dashboard_build_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_user_id'), 'dashboard_build_jobs', ['user_id'], unique=False)
    # op.alter_column('dashboards', 'is_locked',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Boolean(),
    #            postgresql_using='is_locked::boolean',
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'false'::character varying"))
    op.create_index(op.f('ix_dashboards_planet_id'), 'dashboards', ['planet_id'], unique=False)
    op.create_foreign_key(None, 'dashboards', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_data_connections_created_by'), 'data_connections', ['created_by'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_pipelines_query_id'), 'pipelines', ['query_id'], unique=False)
    op.create_index(op.f('ix_pipelines_started_at'), 'pipelines', ['started_at'], unique=False)
    op.drop_constraint('uq_planet_members_planet_user', 'planet_members', type_='unique')
    op.create_index(op.f('ix_planet_members_planet_id'), 'planet_members', ['planet_id'], unique=False)
    op.create_index(op.f('ix_planet_members_user_id'), 'planet_members', ['user_id'], unique=False)
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_space_connections_connection_id'), 'space_connections', ['connection_id'], unique=False)
    op.create_index(op.f('ix_space_connections_space_id'), 'space_connections', ['space_id'], unique=False)
    op.drop_index('idx_space_members_space_id', table_name='space_members')
    op.drop_index('idx_space_members_user_id', table_name='space_members')
    op.create_index(op.f('ix_space_members_space_id'), 'space_members', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_members_user_id'), 'space_members', ['user_id'], unique=False)
    op.drop_constraint('uq_starred_items_user_item', 'starred_items', type_='unique')
    op.add_column('strategic_pillars', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategic_pillars', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategic_pillars_crew_id'), 'strategic_pillars', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategic_pillars_space_id'), 'strategic_pillars', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategic_pillars', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategic_pillars', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategy_assumptions', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategy_assumptions', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategy_assumptions_crew_id'), 'strategy_assumptions', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategy_assumptions_space_id'), 'strategy_assumptions', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategy_assumptions', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_assumptions', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.add_column('strategy_initiatives', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategy_initiatives', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategy_initiatives_crew_id'), 'strategy_initiatives', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategy_initiatives_space_id'), 'strategy_initiatives', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategy_initiatives', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_initiatives', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_table_member_permissions_connection_id'), 'table_member_permissions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_table_member_permissions_crew_id'), 'table_member_permissions', ['crew_id'], unique=False)
    op.create_index(op.f('ix_table_member_permissions_member_id'), 'table_member_permissions', ['member_id'], unique=False)
    op.drop_index('idx_user_enterprise_relationships_created_by', table_name='user_enterprise_relationships')
    op.create_index(op.f('ix_user_enterprise_relationships_created_by'), 'user_enterprise_relationships', ['created_by'], unique=False)
    op.drop_index('idx_users_auth_provider_id', table_name='users', postgresql_where='((auth_provider_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('idx_users_auth0_id', table_name='users', postgresql_where='((auth0_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index('idx_users_auth0_id', 'users', ['auth0_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_widget_connections_dashboard_id'), 'widget_connections', ['dashboard_id'], unique=False)
    op.create_index('idx_widgets_connection_id', 'widgets', ['connection_id'], unique=False)
    op.create_index('idx_widgets_query_id', 'widgets', ['query_id'], unique=False)
    op.create_index(op.f('ix_widgets_connection_id'), 'widgets', ['connection_id'], unique=False)
    op.create_index(op.f('ix_widgets_dashboard_id'), 'widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_widgets_query_id'), 'widgets', ['query_id'], unique=False)
    op.create_foreign_key(None, 'widgets', 'ai_queries', ['query_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'widgets', 'data_connections', ['connection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'widgets', type_='foreignkey')
    op.drop_constraint(None, 'widgets', type_='foreignkey')
    op.drop_index(op.f('ix_widgets_query_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_dashboard_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_connection_id'), table_name='widgets')
    op.drop_index('idx_widgets_query_id', table_name='widgets')
    op.drop_index('idx_widgets_connection_id', table_name='widgets')
    op.drop_index(op.f('ix_widget_connections_dashboard_id'), table_name='widget_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_auth0_id', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_users_auth0_id', 'users', ['auth0_id'], unique=True, postgresql_where='((auth0_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_auth_provider_id', 'users', ['auth_provider_id'], unique=False, postgresql_where='((auth_provider_id IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index(op.f('ix_user_enterprise_relationships_created_by'), table_name='user_enterprise_relationships')
    op.create_index('idx_user_enterprise_relationships_created_by', 'user_enterprise_relationships', ['created_by'], unique=False)
    op.drop_index(op.f('ix_table_member_permissions_member_id'), table_name='table_member_permissions')
    op.drop_index(op.f('ix_table_member_permissions_crew_id'), table_name='table_member_permissions')
    op.drop_index(op.f('ix_table_member_permissions_connection_id'), table_name='table_member_permissions')
    op.drop_constraint(None, 'strategy_initiatives', type_='foreignkey')
    op.drop_constraint(None, 'strategy_initiatives', type_='foreignkey')
    op.drop_index(op.f('ix_strategy_initiatives_space_id'), table_name='strategy_initiatives')
    op.drop_index(op.f('ix_strategy_initiatives_crew_id'), table_name='strategy_initiatives')
    op.drop_column('strategy_initiatives', 'crew_id')
    op.drop_column('strategy_initiatives', 'space_id')
    op.drop_constraint(None, 'strategy_assumptions', type_='foreignkey')
    op.drop_constraint(None, 'strategy_assumptions', type_='foreignkey')
    op.drop_index(op.f('ix_strategy_assumptions_space_id'), table_name='strategy_assumptions')
    op.drop_index(op.f('ix_strategy_assumptions_crew_id'), table_name='strategy_assumptions')
    op.drop_column('strategy_assumptions', 'crew_id')
    op.drop_column('strategy_assumptions', 'space_id')
    op.drop_constraint(None, 'strategic_pillars', type_='foreignkey')
    op.drop_constraint(None, 'strategic_pillars', type_='foreignkey')
    op.drop_index(op.f('ix_strategic_pillars_space_id'), table_name='strategic_pillars')
    op.drop_index(op.f('ix_strategic_pillars_crew_id'), table_name='strategic_pillars')
    op.drop_column('strategic_pillars', 'crew_id')
    op.drop_column('strategic_pillars', 'space_id')
    op.create_unique_constraint('uq_starred_items_user_item', 'starred_items', ['user_id', 'item_id', 'item_type'])
    op.drop_index(op.f('ix_space_members_user_id'), table_name='space_members')
    op.drop_index(op.f('ix_space_members_space_id'), table_name='space_members')
    op.create_index('idx_space_members_user_id', 'space_members', ['user_id'], unique=False)
    op.create_index('idx_space_members_space_id', 'space_members', ['space_id'], unique=False)
    op.drop_index(op.f('ix_space_connections_space_id'), table_name='space_connections')
    op.drop_index(op.f('ix_space_connections_connection_id'), table_name='space_connections')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    op.drop_index(op.f('ix_planet_members_user_id'), table_name='planet_members')
    op.drop_index(op.f('ix_planet_members_planet_id'), table_name='planet_members')
    op.create_unique_constraint('uq_planet_members_planet_user', 'planet_members', ['planet_id', 'user_id'])
    op.drop_index(op.f('ix_pipelines_started_at'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_query_id'), table_name='pipelines')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_data_connections_created_by'), table_name='data_connections')
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_index(op.f('ix_dashboards_planet_id'), table_name='dashboards')
    # op.alter_column('dashboards', 'is_locked',
    #            existing_type=sa.Boolean(),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'false'::character varying"))
    op.drop_index(op.f('ix_dashboard_build_jobs_user_id'), table_name='dashboard_build_jobs')
    op.drop_index(op.f('ix_dashboard_build_jobs_status'), table_name='dashboard_build_jobs')
    op.drop_index(op.f('ix_dashboard_build_jobs_space_id'), table_name='dashboard_build_jobs')
    op.drop_index(op.f('ix_dashboard_build_jobs_planet_id'), table_name='dashboard_build_jobs')
    op.drop_index(op.f('ix_dashboard_build_jobs_dashboard_id'), table_name='dashboard_build_jobs')
    op.drop_index(op.f('ix_dashboard_build_jobs_connection_id'), table_name='dashboard_build_jobs')
    op.create_index('idx_dashboard_build_jobs_user_id', 'dashboard_build_jobs', ['user_id'], unique=False)
    op.create_index('idx_dashboard_build_jobs_status', 'dashboard_build_jobs', ['status'], unique=False)
    op.create_index('idx_dashboard_build_jobs_space_id', 'dashboard_build_jobs', ['space_id'], unique=False)
    op.create_index('idx_dashboard_build_jobs_planet_id', 'dashboard_build_jobs', ['planet_id'], unique=False)
    op.create_index('idx_dashboard_build_jobs_dashboard_id', 'dashboard_build_jobs', ['dashboard_id'], unique=False)
    op.create_index('idx_dashboard_build_jobs_connection_id', 'dashboard_build_jobs', ['connection_id'], unique=False)
    op.drop_index(op.f('ix_crews_space_id'), table_name='crews')
    op.drop_index(op.f('ix_crew_members_user_id'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_members_crew_id'), table_name='crew_members')
    op.drop_index(op.f('ix_crew_connections_crew_id'), table_name='crew_connections')
    op.drop_index(op.f('ix_crew_connections_connection_id'), table_name='crew_connections')
    op.drop_index(op.f('ix_connection_permissions_user_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_permissions_space_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_permissions_crew_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_permissions_connection_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_metadata_connection_id'), table_name='connection_metadata')
    op.create_unique_constraint('uq_connection_metadata_connection_id', 'connection_metadata', ['connection_id'])
    op.drop_index(op.f('ix_comments_widget_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_dashboard_id'), table_name='comments')
    op.create_index('idx_comments_widget_id', 'comments', ['widget_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('idx_comments_dashboard_id', 'comments', ['dashboard_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_widget_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_ai_responses_widget_id'), table_name='ai_responses')
    op.drop_index(op.f('ix_ai_responses_timestamp'), table_name='ai_responses')
    op.drop_index(op.f('ix_ai_responses_is_active'), table_name='ai_responses')
    op.drop_index(op.f('ix_ai_queries_widget_id'), table_name='ai_queries')
    op.drop_index(op.f('ix_ai_queries_user_id'), table_name='ai_queries')
    op.add_column('ai_history', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ai_history_user_id'), table_name='ai_history')
    op.drop_index(op.f('ix_ai_history_pinned'), table_name='ai_history')
    op.drop_index(op.f('ix_ai_history_date'), table_name='ai_history')
    op.drop_index('idx_ai_history_space_id', table_name='ai_history')
    op.drop_index('idx_ai_history_crew_id', table_name='ai_history')
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name='checkpoint_migrations_pkey')
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name='checkpoint_writes_pkey')
    )
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name='checkpoint_blobs_pkey')
    )
    op.create_table('query_audit_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crew_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sql_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chosen_tables', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_rows_returned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('was_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('block_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], name='query_audit_log_connection_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='query_audit_log_space_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='query_audit_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='query_audit_log_pkey')
    )
    op.create_table('chat_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_index('ix_chat_history_thread_id', 'chat_history', ['thread_id'], unique=False)
    op.create_table('user_datasets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dataset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_datasets_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_datasets_pkey'),
    sa.UniqueConstraint('user_id', 'dataset_id', name='uq_user_datasets')
    )
    op.create_index('idx_user_datasets_user_id', 'user_datasets', ['user_id'], unique=False)
    op.create_index('idx_user_datasets_dataset_id', 'user_datasets', ['dataset_id'], unique=False)
    op.create_table('universe_insights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_markdown', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('relevance_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommended_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_impact', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_investigation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hypothesis_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sql_generated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('user_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], name='universe_insights_connection_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='universe_insights_space_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='universe_insights_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='universe_insights_pkey')
    )
    op.create_table('table_metadata',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_connection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crew_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='table_metadata_crew_id_fkey'),
    sa.ForeignKeyConstraint(['data_connection_id'], ['data_connections.id'], name='table_metadata_data_connection_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='table_metadata_space_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='table_metadata_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], name='pipeline_jobs_connection_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pipeline_jobs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pipeline_jobs_pkey')
    )
    op.create_table('semantic_cache',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crew_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('response_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='semantic_cache_pkey')
    )
    op.create_index('ix_semantic_cache_space_id', 'semantic_cache', ['space_id'], unique=False)
    op.create_index('ix_semantic_cache_crew_id', 'semantic_cache', ['crew_id'], unique=False)
    op.create_index('ix_semantic_cache_connection_id', 'semantic_cache', ['connection_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name='checkpoints_pkey')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crew_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='user_permissions_crew_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_permissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_permissions_pkey')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crew_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('table_metadata_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], name='embeddings_crew_id_fkey'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name='embeddings_space_id_fkey'),
    sa.ForeignKeyConstraint(['table_metadata_id'], ['table_metadata.id'], name='embeddings_table_metadata_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='embeddings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='embeddings_pkey')
    )
    op.create_table('universe_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('focus_topics', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('strategic_goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('noise_level', sa.VARCHAR(length=50), server_default=sa.text("'executivo'::character varying"), autoincrement=False, nullable=False),
    sa.Column('allowed_tables', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('focus_external_signals', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deliver_feed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('deliver_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deliver_webhook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='universe_configs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='universe_configs_pkey'),
    sa.UniqueConstraint('user_id', name='universe_configs_user_id_key')
    )
    # ### end Alembic commands ###

