"""add_scope_to_strategy_models_fixed

Revision ID: fd74af4b3c14
Revises: dbb9a0420d3e
Create Date: 2026-03-13 15:29:30.398502

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd74af4b3c14'
down_revision = 'dbb9a0420d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED DROPS: We preserve all existing tables (chat_history, table_metadata, etc.)
    
    # 1. New Indexes for AI History
    op.create_index('idx_ai_history_crew_id', 'ai_history', ['crew_id'], unique=False)
    op.create_index('idx_ai_history_space_id', 'ai_history', ['space_id'], unique=False)
    op.create_index(op.f('ix_ai_history_date'), 'ai_history', ['date'], unique=False)
    op.create_index(op.f('ix_ai_history_pinned'), 'ai_history', ['pinned'], unique=False)
    op.create_index(op.f('ix_ai_history_user_id'), 'ai_history', ['user_id'], unique=False)
    
    # 2. Indexes for AI Queries and Responses
    op.create_index(op.f('ix_ai_queries_user_id'), 'ai_queries', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_queries_widget_id'), 'ai_queries', ['widget_id'], unique=False)
    op.create_index(op.f('ix_ai_responses_is_active'), 'ai_responses', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_responses_timestamp'), 'ai_responses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ai_responses_widget_id'), 'ai_responses', ['widget_id'], unique=False)
    
    # 3. Indexes for Chat Messages and Comments
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_widget_id'), 'chat_messages', ['widget_id'], unique=False)
    
    op.create_index(op.f('ix_comments_dashboard_id'), 'comments', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_widget_id'), 'comments', ['widget_id'], unique=False)
    
    # 4. Permissions and Connections
    op.create_index(op.f('ix_connection_metadata_connection_id'), 'connection_metadata', ['connection_id'], unique=True)
    op.create_index(op.f('ix_connection_permissions_connection_id'), 'connection_permissions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_crew_id'), 'connection_permissions', ['crew_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_space_id'), 'connection_permissions', ['space_id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_user_id'), 'connection_permissions', ['user_id'], unique=False)
    
    # 5. Dashboard Build Jobs
    op.create_index(op.f('ix_dashboard_build_jobs_connection_id'), 'dashboard_build_jobs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_dashboard_id'), 'dashboard_build_jobs', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_planet_id'), 'dashboard_build_jobs', ['planet_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_space_id'), 'dashboard_build_jobs', ['space_id'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_status'), 'dashboard_build_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_dashboard_build_jobs_user_id'), 'dashboard_build_jobs', ['user_id'], unique=False)
    
    # 6. Scoping Strategy Models
    op.create_index(op.f('ix_dashboards_planet_id'), 'dashboards', ['planet_id'], unique=False)
    op.create_foreign_key(None, 'dashboards', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('strategic_pillars', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategic_pillars', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategic_pillars_crew_id'), 'strategic_pillars', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategic_pillars_space_id'), 'strategic_pillars', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategic_pillars', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategic_pillars', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('strategy_assumptions', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategy_assumptions', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategy_assumptions_crew_id'), 'strategy_assumptions', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategy_assumptions_space_id'), 'strategy_assumptions', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategy_assumptions', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_assumptions', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('strategy_initiatives', sa.Column('space_id', sa.UUID(), nullable=True))
    op.add_column('strategy_initiatives', sa.Column('crew_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_strategy_initiatives_crew_id'), 'strategy_initiatives', ['crew_id'], unique=False)
    op.create_index(op.f('ix_strategy_initiatives_space_id'), 'strategy_initiatives', ['space_id'], unique=False)
    op.create_foreign_key(None, 'strategy_initiatives', 'spaces', ['space_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'strategy_initiatives', 'crews', ['crew_id'], ['id'], ondelete='CASCADE')
    
    # 7. Other fixes
    op.create_index(op.f('ix_planet_members_planet_id'), 'planet_members', ['planet_id'], unique=False)
    op.create_index(op.f('ix_planet_members_user_id'), 'planet_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade logic simplified as we removed drops in upgrade
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_planet_members_user_id'), table_name='planet_members')
    op.drop_index(op.f('ix_planet_members_planet_id'), table_name='planet_members')
    
    op.drop_constraint(None, 'strategy_initiatives', type_='foreignkey')
    op.drop_constraint(None, 'strategy_initiatives', type_='foreignkey')
    op.drop_column('strategy_initiatives', 'crew_id')
    op.drop_column('strategy_initiatives', 'space_id')
    
    op.drop_constraint(None, 'strategy_assumptions', type_='foreignkey')
    op.drop_constraint(None, 'strategy_assumptions', type_='foreignkey')
    op.drop_column('strategy_assumptions', 'crew_id')
    op.drop_column('strategy_assumptions', 'space_id')
    
    op.drop_constraint(None, 'strategic_pillars', type_='foreignkey')
    op.drop_constraint(None, 'strategic_pillars', type_='foreignkey')
    op.drop_column('strategic_pillars', 'crew_id')
    op.drop_column('strategic_pillars', 'space_id')
    
    op.drop_index(op.f('ix_ai_history_user_id'), table_name='ai_history')
    op.drop_index('idx_ai_history_space_id', table_name='ai_history')
    op.drop_index('idx_ai_history_crew_id', table_name='ai_history')
